version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies with npm ci..."
      - npm ci
  build:
    commands:
      - echo "--- Listing files AFTER npm ci ---"
      - ls -la
      - echo "----------------------------------"
artifacts:
  files:
    - '**/*'