service: astronomyshare-api

frameworkVersion: '4'

provider:
  httpApi:
    cors:
      allowedOrigins:
        - 'http://localhost:3000'
        - 'https://dev.astronomyshare.com'
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - OPTIONS
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    REACT_APP_COGNITO_USER_POOL_ID: ${env:REACT_APP_COGNITO_USER_POOL_ID}
    FRONTEND_URL: ${env:FRONTEND_URL}

plugins:
 - serverless-dotenv-plugin 
 - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000

functions:
  registerUser:
    handler: src/register-handler/index.handler
    events:
      - httpApi:
          path: /register
          method: post

package:
  individually: true
  exclude:
    - './**'
  include:
    - 'src/register-handler/index.js'
    - 'src/register-handler/package.json'
    - 'src/register-handler/node_modules/**'
    - 'src/shared/**'